### PR TITLE
[JENKINS-46004] Bump stapler-adjunct-jquery

### PR DESCRIPTION
**Pull request by ghost**
https://issues.jenkins-ci.org/browse/JENKINS-46004

https://github.com/stapler/stapler-adjunct-jquery/pull/1

@reviewbybees @jglick

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
Has this been at least interactively tested in conjunction with any of the plugins depending on this one to make sure basic scenarios work?

**Comment by ghost** [comment]
I did some smoke testing back when this ticket was originally raised and everything looked OK.

**Comment by jglick** [comment]
OK, I guess I will merge & release shortly then.

**Comment by ghost** [comment]
@reviewbybees done

**Pull request merged**
